import React, { useState } from "react";
import { MdAddBox } from "react-icons/md";

const Form = ({
  task,
  setTask,
  input,
  setInput,
  status,
  setStatus,
  filtered,
  setFiltered,
}) => {
  let priority;

  //It handles the change on the text-box and updates that input to the list.
  //Then It empties the box.
  const handleChange = (e) => {
    e.preventDefault();
    task && tAdd(task);
    setTask("");
  };

  //When the new input is updated, unique id to identify the list is generated by the length.
  //Task is updated as the user input.
  //Conditions are saved as default value. If a user presses 'shift+enter' button together,
  //'priority' variable becomes true, which changes sorting to 1.
  const tAdd = (text) => {
    let addInput = [
      ...input,
      {
        id: input.length + 1,
        task: text,
        isCompleted: false,
        isEditMode: false,
        isPriority: priority,
        sorting: priority == true ? 1 : 0,
      },
    ];
    setInput(addInput);
  };

  //To update the completion status according to user's click event.
  const tFilter = (e) => {
    setStatus("");
    if (e.target.value == "completed") {
      setStatus("completed");
    } else if (e.target.value == "incompleted") {
      setStatus("incompleted");
    } else if (e.target.value == "all") {
      setStatus("all");
    }
  };

  //if a user presses "shift" with "Enter/c", priority variable becomes true, otherwise false as a default.
  const keyPress = (e) => {
    priority = e.shiftKey ? true : false;
  };
  return (
    <form onSubmit={handleChange}>
      <input
        value={task}
        type="text"
        placeholder="type here"
        onChange={(e) => setTask(e.target.value)}
        onKeyPress={keyPress}
      ></input>
      <MdAddBox
        className="button"
        id="addBtn"
        type="submit"
        onClick={handleChange}
      />
      <div className="button" id="box">
        <select name="todos" class="filter-todo" onChange={tFilter}>
          <option value="all">All</option>
          <option value="completed">Completed</option>
          <option value="incompleted">Incompleted</option>
        </select>
      </div>
    </form>
  );
};

export default Form;
